'use strict';
(() => {
  const colors=['#155d91','#a64538','#387965','#7b858a'];
  const dash=['','7 4','3 3','10 4 2 4'];
  const NS='http://www.w3.org/2000/svg';
  let data;
  const $=id=>document.getElementById(id);
  const fmt=(v,n=1)=>v==null?'欠損':v.toLocaleString('ja-JP',{minimumFractionDigits:n,maximumFractionDigits:n});
  const pct=v=>(v>0?'+':'')+fmt(v)+'%';
  const cut={ '6m':'2026-03-15','5y':'2021-09-15'};
  function el(tag,attrs={},txt){const e=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);if(txt!==undefined)e.textContent=txt;return e;}
  function base(id,title,period,height){const box=$(id);box.replaceChildren();const w=Math.max(260,Math.round(box.clientWidth));const t=document.createElement('p');t.className='chart-title';t.textContent=title;box.append(t);const p=document.createElement('p');p.className='chart-period';p.textContent=period;box.append(p);const svg=el('svg',{viewBox:`0 0 ${w} ${height}`,role:'img','aria-label':title+'。'+period});svg.append(el('title',{},title+'。'+period));box.append(svg);return{box,w,svg,height};}
  function legend(box,labels){const ul=document.createElement('ul');ul.className='legend';labels.forEach((label,i)=>{const li=document.createElement('li'),key=document.createElement('i');key.style.borderColor=colors[i];if(i)key.style.borderTopStyle=i===2?'dotted':'dashed';li.append(key,document.createTextNode(label));ul.append(li)});box.append(ul);}
  function line(id,names,range,title,unit,fixed){
    const start=cut[range]||range,end=data.asof;
    const {box,w,svg}=base(id,title,`${range==='6m'?'直近6か月':'過去5年'} · ${start.replaceAll('-','/')} — ${end.replaceAll('-','/')} · ${unit}`,252);
    const L=w<380?48:55,R=13,T=12,B=28,H=252,ph=H-T-B,pw=w-L-R;
    const arrays=names.map(n=>data.series[n].filter(([d])=>d>=start&&d<=end));
    const missing=range==='5y'?names.map(n=>[n,data.series[n].filter(([,v])=>Number.isFinite(v))[0]?.[0]]).filter(([,d])=>d&&d>start):[];
    if(missing.length){box.querySelector('.chart-period').textContent+=` · 5年未満：${missing.map(([n,d])=>`${data.labels[n]} ${d.replaceAll('-','/')}`).join('、')}`;}
    const vals=arrays.flat().map(p=>p[1]).filter(Number.isFinite);let low,high;
    if(fixed){[low,high]=fixed;}else{low=Math.min(...vals);high=Math.max(...vals);const pad=(high-low||high*.01)*.12;low-=pad;high+=pad;}
    const t0=Date.parse(start),t1=Date.parse(end),X=d=>L+(Date.parse(d)-t0)/(t1-t0)*pw,Y=v=>T+(high-v)/(high-low)*ph;
    const tickDecimals=(high-low)/4<.01?3:(high-low)/4<1?2:(high-low)/4<10?1:0;
    for(let i=0;i<5;i++){const value=low+(high-low)*i/4,y=Y(value);svg.append(el('line',{x1:L,x2:w-R,y1:y,y2:y,class:'grid'}));svg.append(el('text',{x:L-7,y:y+4,'text-anchor':'end',class:'axis'},fmt(value,tickDecimals)));}
    for(let i=0;i<3;i++){const tm=t0+(t1-t0)*i/2,d=new Date(tm),label=range==='5y'?`${d.getUTCFullYear()}/${d.getUTCMonth()+1}`:`${d.getUTCMonth()+1}/${d.getUTCDate()}`;svg.append(el('text',{x:L+pw*i/2,y:H-6,'text-anchor':i===0?'start':i===2?'end':'middle',class:'axis'},label));}
    arrays.forEach((points,i)=>{let active=false,d='';for(const[date,val]of points){if(val===null){active=false;continue;}d+=(active?'L':'M')+X(date).toFixed(2)+','+Y(val).toFixed(2);active=true;}svg.append(el('path',{d,class:'chart-line',stroke:colors[i],'stroke-dasharray':dash[i]}));});
    const cross=el('line',{x1:0,x2:0,y1:T,y2:H-B,class:'crosshair',visibility:'hidden'});svg.append(cross);
    const overlay=el('rect',{x:L,y:T,width:pw,height:ph,fill:'transparent'});svg.append(overlay);
    legend(box,names.map(n=>n.includes('|')?data.labels[n]:data.labels[n].split('｜')[0]));
    const read=document.createElement('div');read.className='chart-readout';read.textContent='図に触れると日付と数値を表示';box.append(read);
    const tip=document.createElement('div');tip.className='tip';box.append(tip);
    const days=arrays[0].map(p=>p[0]),maps=arrays.map(a=>new Map(a));let cursor=days.length-1;
    function show(index,event){cursor=Math.max(0,Math.min(days.length-1,index));const date=days[cursor],x=X(date);cross.setAttribute('x1',x);cross.setAttribute('x2',x);cross.setAttribute('visibility','visible');tip.replaceChildren();const b=document.createElement('strong');b.textContent=date;tip.append(b);names.forEach((n,i)=>{const span=document.createElement('span');span.textContent=(n.includes('|')?data.labels[n]:data.labels[n].split('｜')[0])+' '+fmt(maps[i].get(date),unit==='価格比率'?4:2);tip.append(span)});tip.style.display='block';tip.style.left=Math.max(0,Math.min(w-210,x+10))+'px';tip.style.top='55px';read.textContent=date+' · '+names.map((n,i)=>(n.includes('|')?data.labels[n]:data.labels[n].split('｜')[0])+': '+fmt(maps[i].get(date),2)).join(' / ');}
    overlay.addEventListener('pointermove',ev=>{const b=svg.getBoundingClientRect(),x=(ev.clientX-b.left)/b.width*w,tm=t0+(x-L)/pw*(t1-t0);let nearest=0,dist=Infinity;days.forEach((d,i)=>{const delta=Math.abs(Date.parse(d)-tm);if(delta<dist){dist=delta;nearest=i}});show(nearest,ev)});
    overlay.addEventListener('pointerleave',()=>{tip.style.display='none';cross.setAttribute('visibility','hidden')});
    box.tabIndex=0;box.setAttribute('aria-label',title+'。左右キーで日付の数値を確認');box.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();show(cursor+(e.key==='ArrowRight'?1:-1))}};box.onblur=()=>{tip.style.display='none';cross.setAttribute('visibility','hidden')};
  }
  const compared=['AMEX:SPY','AMEX:RSP','NASDAQ:QQQ','AMEX:IWM','NASDAQ:SOX','AMEX:SPHB','AMEX:SPLV','CBOE:MAGS','AMEX:XLV','AMEX:XLP'];
  function returns(id,key){const[label,start]=data.periods[key],rows=compared.map(n=>({n,v:data.metrics[n][key+'_pct']})).sort((a,b)=>b.v-a.v);const mob=$(id).clientWidth<500,h=rows.length*(mob?51:38)+38;const{svg,w}=base(id,'強い順に比較',`${label} · ${start} → ${data.asof} · %`,h);const L=mob?15:205,R=55,pw=w-L-R;const lo=Math.min(0,...rows.map(x=>x.v)),hi=Math.max(0,...rows.map(x=>x.v)),pad=Math.max((hi-lo)*.07,.2),X=v=>L+(v-(lo-pad))/(hi-lo+pad*2)*pw;const top=20;svg.append(el('line',{x1:X(0),x2:X(0),y1:0,y2:h-20,class:'zero'}));rows.forEach((r,i)=>{const y=top+i*(mob?51:38);const label=data.labels[r.n];svg.append(el('text',{x:mob?L:0,y:mob?y-4:y+4,class:'axis'},label));const by=mob?y+7:y-7;svg.append(el('rect',{x:Math.min(X(0),X(r.v)),y:by,width:Math.max(1,Math.abs(X(r.v)-X(0))),height:13,fill:r.v<0?colors[1]:colors[0]}));svg.append(el('text',{x:w,y:by+12,'text-anchor':'end',class:'rank-value'},pct(r.v)));});}
  function rank(id,names,title){const mob=$(id).clientWidth<550,step=mob?68:48,h=names.length*step+48;const{svg,w,box}=base(id,title,'低い位置 0 ← 過去の観測日分布 → 100 高い位置',h);const L=mob?12:180,R=mob?10:125,pw=w-L-R,X=v=>L+v/100*pw;[0,25,50,75,100].forEach(v=>{svg.append(el('line',{x1:X(v),x2:X(v),y1:23,y2:h-14,class:'grid'}));svg.append(el('text',{x:X(v),y:13,'text-anchor':v===0?'start':v===100?'end':'middle',class:'axis'},String(v)))});names.forEach((n,i)=>{const r=data.ranks[n],y=43+i*step+(mob?17:0);svg.append(el('text',{x:mob?L:0,y:mob?y-18:y+4,class:'axis'},data.labels[n]));svg.append(el('line',{x1:X(0),x2:X(100),y1:y,y2:y,stroke:'#cbd2d6','stroke-width':5}));if(r.previous!==null){svg.append(el('line',{x1:X(r.previous),x2:X(r.now),y1:y,y2:y,class:'rank-connector'}));svg.append(el('circle',{cx:X(r.previous),cy:y,r:5,fill:'#fff',stroke:colors[1],'stroke-width':1.5}));}const dot=el('circle',{cx:X(r.now),cy:y,r:5.5,fill:colors[0]});dot.append(el('title',{},`${data.labels[n]} 現在 ${fmt(r.now)}、前週値 ${fmt(r.previous)}パーセンタイル`));svg.append(dot);svg.append(el('text',{x:mob?w:w-2,y:mob?y-18:y+4,'text-anchor':'end',class:'rank-value'},fmt(r.now)+' pct'));});const note=document.createElement('p');note.className='chart-readout';note.textContent='● 現在値の順位　○ 9月8日の値の順位（同じ履歴で比較）';box.append(note);}
  const pair=(host,id,title,names,unit,fixed)=>{const node=$(host);node.replaceChildren();node.className='chart-grid pair-grid';for(const [range,label] of [['6m','直近6か月'],['5y','過去5年']]){const box=document.createElement('div');box.className='chart';box.id=`${id}-${range}`;node.append(box);line(box.id,names,range,`${title}｜${label}`,unit,fixed);}};
  function setup(){
    const spy=$('chart-spy');if(spy)spy.id='pair-spy';const ret=$('chart-returns');if(ret){ret.id='pair-returns';const month=document.createElement('div');month.id='chart-returns-1m';ret.after(month);}
    const ratios=$('chart-rsp-ratio');if(ratios){ratios.id='pair-ratios';$('chart-beta-ratio').remove();const beta=document.createElement('div');beta.id='pair-beta-ratio';ratios.after(beta);}
    const breadth=$('chart-breadth-short');if(breadth){breadth.id='pair-breadth-short';$('chart-breadth-long').id='pair-breadth-long';}
    const vix=$('chart-vix');if(vix){const f=vix.closest('figure');f.querySelector('#chart-cor').remove();f.querySelector('#chart-vixeq').remove();vix.id='pair-vix';const cor=document.createElement('div');cor.id='pair-cor';const eq=document.createElement('div');eq.id='pair-vixeq';vix.after(cor,eq);}
    const dip=$('chart-dip-beta');if(dip){dip.id='pair-dip-beta';const sox=$('chart-dip-sox');sox.id='pair-dip-sox';}}
  function all(){pair('pair-spy','spy','SPYと20・50・200日平均',['AMEX:SPY','AMEX:SPY|MA20','AMEX:SPY|MA50','AMEX:SPY|MA200'],'米ドル');returns('pair-returns','5d');returns('chart-returns-1m','1m');rank('chart-relative',['RSP/SPY','QQQE/QQQ','SPHB/SPLV','GDX/GLD'],'相対比率の長期順位');pair('pair-ratios','rsp-ratio','均等加重 / 時価総額加重',['RSP/SPY'],'価格比率');pair('pair-beta-ratio','beta-ratio','高ベータ / 低ボラ',['SPHB/SPLV'],'価格比率');pair('pair-breadth-short','breadth-short','市場参加：20日平均超え',['INDEX:S5TW','INDEX:NDTW'],'構成銘柄比率 %',[0,100]);pair('pair-breadth-long','breadth-long','市場参加：200日平均超え',['INDEX:S5TH','INDEX:NDTH'],'構成銘柄比率 %',[0,100]);pair('pair-vix','vix','指数の予想変動率',['CBOE:VIX','CBOE:VIX9D'],'年率 %');pair('pair-cor','cor','予想相関',['CBOE:COR1M','CBOE:COR3M'],'指数ポイント');pair('pair-vixeq','vixeq','個別株の予想変動率',['CBOE:VIXEQ'],'年率 %');rank('chart-risk-rank',['CBOE:VIX','CBOE:COR1M','TVC:US10Y','FRED:BAMLH0A0HYM2'],'各系列内の長期順位');pair('pair-dip-beta','dip-beta','SPHB｜高ベータ株',['AMEX:SPHB','AMEX:SPHB|MA20','AMEX:SPHB|MA50','AMEX:SPHB|MA200'],'米ドル');pair('pair-dip-sox','dip-sox','SOX｜半導体指数',['NASDAQ:SOX','NASDAQ:SOX|MA20','NASDAQ:SOX|MA50','NASDAQ:SOX|MA200'],'指数ポイント');}
  async function boot(){const response=await fetch('market-review-data.json?v=20260916');if(!response.ok)throw new Error('図のデータを取得できません');data=await response.json();if(data.asof!=='2026-09-15')throw new Error('本文と図の基準日が一致しません');setup();all();document.querySelectorAll('details').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)all()}));let timer;window.addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(all,150)});document.documentElement.dataset.chartsReady='true';window.marketReview={data};}
  boot().catch(error=>{document.querySelectorAll('.chart').forEach(box=>{box.textContent=error.message+'。下部のCSVで数値を確認できます。';box.classList.add('chart-error')});console.error(error)});
})();
